/**
 * POST /api/webhooks/greenapi?t=<GREENAPI_WEBHOOK_TOKEN>
 *
 * Приёмник событий Green-API. Обрабатываем:
 *   • incomingMessageReceived     — клиент написал нам → INSERT deal_messages
 *   • outgoingMessageStatus       — обновление статуса наших исходящих
 *   • outgoingMessageReceived     — исходящее с телефона (оператор ответил из WA)
 *   • stateInstanceChanged        — логируем для отладки
 *
 * Match входящего номера → сделка: по deals.contact_phone или patients.phone.
 * Если нет сделки — создаём новую в первой стадии первой «медицинской» воронки.
 *
 * Идемпотентность: deal_messages.external_id UNIQUE по (channel, external_id)
 * — повторная доставка webhook-а не создаст дубли.
 */

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import {
  extractIncomingText,
  extractSenderName,
  type GreenApiWebhook,
  type IncomingMessageWebhook,
  type OutgoingStatusWebhook,
} from '@/lib/greenapi'

// Service-role client: webhook прилетает без auth-куки.
function admin() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  )
}

function chatIdToPhone(chatId: string): string {
  // "77051234567@c.us" → "77051234567"
  return chatId.split('@')[0].replace(/\D/g, '')
}

type DealRef = { id: string; clinic_id: string; name?: string | null }

/**
 * Если у сделки ещё нет «настоящего» имени (только номер / плейсхолдер
 * вида "WhatsApp: +7…"), а в вебхуке пришло имя из WA — подставляем его.
 * Имя, введённое оператором вручную, не трогаем.
 */
async function maybeBackfillDealName(
  dealId: string,
  currentName: string | null | undefined,
  phone: string,
  waName: string | null,
): Promise<void> {
  if (!waName) return
  const cur = (currentName ?? '').trim()
  const looksAutogenerated =
    cur === '' ||
    cur === phone ||
    cur === `+${phone}` ||
    /^whatsapp[: ]/i.test(cur) ||
    /^\+?[\d\s()-]+$/.test(cur) // только цифры/плюс/скобки = телефон
  if (!looksAutogenerated) return
  const { error } = await admin().from('deals').update({ name: waName }).eq('id', dealId)
  if (error) {
    console.warn('[greenapi] failed to backfill deal.name:', error.message)
  } else {
    console.log('[greenapi] deal.name updated →', waName)
  }
}

async function findDealByPhone(phone: string): Promise<DealRef | null> {
  const db = admin()
  if (!phone || phone.length < 7) return null
  const tail = phone.slice(-10)

  const { data } = await db
    .from('deals')
    .select('id, clinic_id, status, name')
    .or(`contact_phone.ilike.%${tail}%`)
    .order('updated_at', { ascending: false })
    .limit(5)

  if (data && data.length > 0) {
    const pick = data.find((d: { status: string }) => d.status === 'open') ?? data[0]
    return { id: pick.id, clinic_id: pick.clinic_id, name: pick.name }
  }

  // patients.phones — text[]. PostgREST containment `cs.{value}` требует
  // точного совпадения элемента, поэтому прогоняем несколько вариантов
  // нормализации номера.
  const variants = Array.from(new Set([phone, `+${phone}`, tail, `+${tail}`]))
  const orExpr = variants.map((v) => `phones.cs.{${v}}`).join(',')
  const { data: pats } = await db
    .from('patients')
    .select('id, clinic_id')
    .or(orExpr)
    .limit(5)

  if (pats && pats.length > 0) {
    const patientIds = pats.map((p: { id: string }) => p.id)
    const { data: deals } = await db
      .from('deals')
      .select('id, clinic_id, status, name')
      .in('patient_id', patientIds)
      .order('updated_at', { ascending: false })
      .limit(5)
    if (deals && deals.length > 0) {
      const pick = deals.find((d: { status: string }) => d.status === 'open') ?? deals[0]
      return { id: pick.id, clinic_id: pick.clinic_id, name: pick.name }
    }
  }

  return null
}

/** Создать «Входящий лид» в первой стадии первой воронки. */
async function createInboundDeal(phone: string, waName: string | null): Promise<DealRef | null> {
  const db = admin()

  // clinic_id живёт на pipelines, не на pipeline_stages — джойним.
  const { data: stage, error: stageErr } = await db
    .from('pipeline_stages')
    .select('id, pipeline_id, pipeline:pipelines(clinic_id)')
    .eq('is_active', true)
    .order('sort_order', { ascending: true })
    .limit(1)
    .maybeSingle()

  if (stageErr) {
    console.error('[greenapi] pipeline_stages query failed:', stageErr.message)
    return null
  }
  if (!stage) {
    console.error('[greenapi] no pipeline_stages row — нужно создать воронку')
    return null
  }

  const pipelineRel = Array.isArray(stage.pipeline) ? stage.pipeline[0] : stage.pipeline
  const clinicId = (pipelineRel as { clinic_id?: string } | null)?.clinic_id
  if (!clinicId) {
    console.error('[greenapi] stage has no linked clinic via pipelines')
    return null
  }

  // Если в WA у собеседника задано имя — используем его без префикса.
  // Иначе ставим номер (чтобы в списке сделок сразу было видно, с кем чат).
  const dealName = waName ?? `+${phone}`

  // Legacy NOT NULL columns: funnel + stage (текстовые enum-ы, живут рядом с
  // новыми pipeline_id/stage_id). Без них insert падает 23502.
  const payload: Record<string, unknown> = {
    clinic_id: clinicId,
    pipeline_id: stage.pipeline_id,
    stage_id: stage.id,
    funnel: 'medical',
    stage: 'new',
    name: dealName,
    contact_phone: phone,
    status: 'open',
  }

  let { data: deal, error } = await db.from('deals').insert(payload).select('id, clinic_id, name').single()

  if (error && /contact_phone|source|column/.test(error.message)) {
    console.warn('[greenapi] deals insert failed on extra cols, retry minimal:', error.message)
    const minimal = {
      clinic_id: clinicId,
      pipeline_id: stage.pipeline_id,
      stage_id: stage.id,
      funnel: 'medical',
      stage: 'new',
      name: dealName,
      status: 'open',
    }
    ;({ data: deal, error } = await db.from('deals').insert(minimal).select('id, clinic_id, name').single())
  }

  if (error || !deal) {
    console.error('[greenapi] createInboundDeal failed:', error?.message)
    return null
  }
  return { id: deal.id, clinic_id: deal.clinic_id, name: deal.name }
}

async function handleIncomingMessage(wh: IncomingMessageWebhook) {
  const db = admin()
  const phone = chatIdToPhone(wh.senderData.chatId)
  const text = extractIncomingText(wh)
  const waName = extractSenderName(wh.senderData)
  console.log(
    '[greenapi] incoming from', phone,
    waName ? `(${waName})` : '(no name)',
    '— text:', text?.slice(0, 80)
  )
  if (!text) return

  let deal = await findDealByPhone(phone)
  if (!deal) {
    console.log('[greenapi] no matching deal, creating inbound lead')
    deal = await createInboundDeal(phone, waName)
    if (!deal) {
      console.error('[greenapi] createInboundDeal returned null — no pipeline_stages?')
      return
    }
    console.log('[greenapi] created deal', deal.id, 'clinic', deal.clinic_id, 'name', deal.name)
  } else {
    console.log('[greenapi] matched existing deal', deal.id, 'name', deal.name)
    // Если раньше имени не было (была автогенерация), а сейчас пришло — обновим.
    await maybeBackfillDealName(deal.id, deal.name, phone, waName)
  }

  // Пробуем полную вставку со статусом, если колонки ещё нет (миграция 040 не
  // применена) — откатываемся на минимальный набор полей.
  const basePayload = {
    deal_id: deal.id,
    clinic_id: deal.clinic_id,
    direction: 'in' as const,
    channel: 'whatsapp' as const,
    body: text,
    external_id: wh.idMessage,
    external_sender: waName ?? phone,
    created_at: new Date(wh.timestamp * 1000).toISOString(),
  }

  let { error } = await db.from('deal_messages').insert({ ...basePayload, status: 'delivered' })
  if (error && /status|column/.test(error.message)) {
    console.warn('[greenapi] status column missing, retrying without it:', error.message)
    ;({ error } = await db.from('deal_messages').insert(basePayload))
  }
  if (error) {
    if (/duplicate/.test(error.message)) {
      console.log('[greenapi] duplicate message ignored:', wh.idMessage)
    } else {
      console.error('[greenapi] insert deal_messages failed:', error.message)
      throw new Error(error.message)
    }
  } else {
    console.log('[greenapi] message saved, deal', deal.id)
  }
}

async function handleOutgoingStatus(wh: OutgoingStatusWebhook) {
  const db = admin()
  const mapped =
    wh.status === 'sent'      ? 'sent' :
    wh.status === 'delivered' ? 'delivered' :
    wh.status === 'read'      ? 'read' :
    wh.status === 'failed' || wh.status === 'noAccount' || wh.status === 'notInGroup'
                              ? 'failed'
                              : null
  if (!mapped) return

  await db
    .from('deal_messages')
    .update({
      status: mapped,
      error_text: mapped === 'failed' ? `GreenAPI: ${wh.status}` : null,
    })
    .eq('external_id', wh.idMessage)
}

export async function POST(req: NextRequest) {
  // 1. Проверяем secret
  const secret = process.env.GREENAPI_WEBHOOK_TOKEN
  const token = req.nextUrl.searchParams.get('t') ?? req.headers.get('x-green-api-token')
  if (secret && token !== secret) {
    return NextResponse.json({ error: 'forbidden' }, { status: 403 })
  }

  // 2. Парсим
  let wh: GreenApiWebhook
  try {
    wh = await req.json()
  } catch {
    return NextResponse.json({ error: 'bad json' }, { status: 400 })
  }

  try {
    if (wh.typeWebhook === 'incomingMessageReceived') {
      await handleIncomingMessage(wh as IncomingMessageWebhook)
    } else if (wh.typeWebhook === 'outgoingMessageStatus') {
      await handleOutgoingStatus(wh as OutgoingStatusWebhook)
    } else if (wh.typeWebhook === 'stateInstanceChanged') {
      console.log('[greenapi] state:', (wh as { stateInstance?: string }).stateInstance)
    }
    return NextResponse.json({ ok: true })
  } catch (err) {
    console.error('[greenapi webhook] error:', err)
    // Возвращаем 200 чтобы GreenAPI не ретраил штормом;
    // внутренние ошибки логируем и разбираем отдельно.
    return NextResponse.json({ ok: false, error: String(err) })
  }
}

// GreenAPI иногда делает GET /healthcheck — отвечаем 200
export async function GET() {
  return NextResponse.json({ ok: true, service: 'greenapi-webhook' })
}
