/**
 * POST /api/webhooks/greenapi?t=<GREENAPI_WEBHOOK_TOKEN>
 *
 * Приёмник событий Green-API. Обрабатываем:
 *   • incomingMessageReceived     — клиент написал нам → INSERT deal_messages
 *   • outgoingMessageStatus       — обновление статуса наших исходящих
 *   • outgoingMessageReceived     — исходящее с телефона (оператор ответил из WA)
 *   • stateInstanceChanged        — логируем для отладки
 *
 * Match входящего номера → сделка: по deals.contact_phone или patients.phone.
 * Если нет сделки — создаём новую в первой стадии первой «медицинской» воронки.
 *
 * Идемпотентность: deal_messages.external_id UNIQUE по (channel, external_id)
 * — повторная доставка webhook-а не создаст дубли.
 */

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import {
  extractIncomingText,
  extractSenderName,
  type GreenApiWebhook,
  type IncomingMessageWebhook,
  type OutgoingStatusWebhook,
} from '@/lib/greenapi'

// Service-role client: webhook прилетает без auth-куки.
function admin() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  )
}

function chatIdToPhone(chatId: string): string {
  // "77051234567@c.us" → "77051234567"
  return chatId.split('@')[0].replace(/\D/g, '')
}

type DealRef = { id: string; clinic_id: string; name?: string | null }

/**
 * Если у сделки ещё нет «настоящего» имени (только номер / плейсхолдер
 * вида "WhatsApp: +7…"), а в вебхуке пришло имя из WA — подставляем его.
 * Имя, введённое оператором вручную, не трогаем.
 */
async function maybeBackfillDealName(
  dealId: string,
  currentName: string | null | undefined,
  phone: string,
  waName: string | null,
): Promise<void> {
  if (!waName) return
  const cur = (currentName ?? '').trim()
  const looksAutogenerated =
    cur === '' ||
    cur === phone ||
    cur === `+${phone}` ||
    /^whatsapp[: ]/i.test(cur) ||
    /^\+?[\d\s()-]+$/.test(cur) // только цифры/плюс/скобки = телефон
  if (!looksAutogenerated) return
  const { error } = await admin().from('deals').update({ name: waName }).eq('id', dealId)
  if (error) {
    console.warn('[greenapi] failed to backfill deal.name:', error.message)
  } else {
    console.log('[greenapi] deal.name updated →', waName)
  }
}

async function findDealByPhone(phone: string): Promise<DealRef | null> {
  const db = admin()
  if (!phone || phone.length < 7) return null
  const tail = phone.slice(-10)

  const { data } = await db
    .from('deals')
    .select('id, clinic_id, status, name')
    .or(`contact_phone.ilike.%${tail}%`)
    .order('updated_at', { ascending: false })
    .limit(5)

  if (data && data.length > 0) {
    const pick = data.find((d: { status: string }) => d.status === 'open') ?? data[0]
    return { id: pick.id, clinic_id: pick.clinic_id, name: pick.name }
  }

  // patients.phones — text[]. PostgREST containment `cs.{value}` требует
  // точного совпадения элемента, поэтому прогоняем несколько вариантов
  // нормализации номера.
  const variants = Array.from(new Set([phone, `+${phone}`, tail, `+${tail}`]))
  const orExpr = variants.map((v) => `phones.cs.{${v}}`).join(',')
  const { data: pats } = await db
    .from('patients')
    .select('id, clinic_id')
    .or(orExpr)
    .limit(5)

  if (pats && pats.length > 0) {
    const patientIds = pats.map((p: { id: string }) => p.id)
    const { data: deals } = await db
      .from('deals')
      .select('id, clinic_id, status, name')
      .in('patient_id', patientIds)
      .order('updated_at', { ascending: false })
      .limit(5)
    if (deals && deals.length > 0) {
      const pick = deals.find((d: { status: string }) => d.status === 'open') ?? deals[0]
      return { id: pick.id, clinic_id: pick.clinic_id, name: pick.name }
    }
  }

  return null
}

/** Создать «Входящий лид» в первой стадии первой воронки. */
async function createInboundDeal(phone: string, waName: string | null): Promise<DealRef | null> {
  const db = admin()

  // clinic_id живёт на pipelines, не на pipeline_stages — джойним.
  const { data: stage, error: stageErr } = await db
    .from('pipeline_stages')
    .select('id, pipeline_id, pipeline:pipelines(clinic_id)')
    .eq('is_active', true)
    .order('sort_order', { ascending: true })
    .limit(1)
    .maybeSingle()

  if (stageErr) {
    console.error('[greenapi] pipeline_stages query failed:', stageErr.message)
    return null
  }
  if (!stage) {
    console.error('[greenapi] no pipeline_stages row — нужно создать воронку')
    return null
  }

  const pipelineRel = Array.isArray(stage.pipeline) ? stage.pipeline[0] : stage.pipeline
  const clinicId = (pipelineRel as { clinic_id?: string } | null)?.clinic_id
  if (!clinicId) {
    console.error('[greenapi] stage has no linked clinic via pipelines')
    return null
  }

  // Бот включён в настройках клиники? clinics.settings — JSONB, читаем плоско.
  // Если настройка отсутствует — bot_enabled считаем false (бот по умолчанию OFF).
  const { data: clinicRow } = await db
    .from('clinics')
    .select('settings')
    .eq('id', clinicId)
    .maybeSingle()
  const botEnabled = (clinicRow?.settings as { bot_enabled?: boolean } | null)?.bot_enabled === true

  // Если в WA у собеседника задано имя — используем его без префикса.
  // Иначе ставим номер (чтобы в списке сделок сразу было видно, с кем чат).
  const dealName = waName ?? `+${phone}`

  // Авто-источник: находим запись «WhatsApp» в справочнике lead_sources.
  // Сид из миграции 036 гарантирует наличие, но если кто-то удалил — создадим.
  let waSourceId: string | null = null
  {
    const { data: existing } = await db
      .from('lead_sources')
      .select('id')
      .eq('clinic_id', clinicId)
      .ilike('name', 'whatsapp')
      .maybeSingle()
    if (existing?.id) {
      waSourceId = existing.id
    } else {
      const { data: created, error: createErr } = await db
        .from('lead_sources')
        .insert({ clinic_id: clinicId, name: 'WhatsApp', sort_order: 20, is_active: true })
        .select('id')
        .single()
      if (createErr) {
        console.warn('[greenapi] lead_sources WhatsApp seed failed:', createErr.message)
      } else {
        waSourceId = created.id
      }
    }
  }

  // Legacy NOT NULL columns: funnel + stage (текстовые enum-ы, живут рядом с
  // новыми pipeline_id/stage_id). Без них insert падает 23502.
  const payload: Record<string, unknown> = {
    clinic_id: clinicId,
    pipeline_id: stage.pipeline_id,
    stage_id: stage.id,
    funnel: 'medical',
    stage: 'new',
    name: dealName,
    contact_phone: phone,
    status: 'open',
    // Включаем бота сразу при insert — cron подхватит на ближайшем тике (≤5 мин).
    // Если bot_enabled=false на уровне клиники, ставим false: меньше работы для cron.
    bot_active: botEnabled,
    ...(waSourceId ? { source_id: waSourceId } : {}),
  }

  let { data: deal, error } = await db.from('deals').insert(payload).select('id, clinic_id, name').single()

  if (error && /contact_phone|source|column|bot_active/.test(error.message)) {
    console.warn('[greenapi] deals insert failed on extra cols, retry minimal:', error.message)
    const minimal = {
      clinic_id: clinicId,
      pipeline_id: stage.pipeline_id,
      stage_id: stage.id,
      funnel: 'medical',
      stage: 'new',
      name: dealName,
      status: 'open',
    }
    ;({ data: deal, error } = await db.from('deals').insert(minimal).select('id, clinic_id, name').single())
  }

  if (error || !deal) {
    console.error('[greenapi] createInboundDeal failed:', error?.message)
    return null
  }
  return { id: deal.id, clinic_id: deal.clinic_id, name: deal.name }
}

/**
 * Авто-подтверждение приёма: если пациент в ответ на 24ч/2ч-напоминание
 * пишет "+" / "да" / "ok" / "yes" — ближайший pending-визит переводится
 * в confirmed, менеджеру не нужно звонить.
 *
 * Логика защиты от ложных срабатываний:
 *   • смотрим только короткие (<=8 символов) сообщения,
 *   • только в окне ближайших 48ч до приёма (чтобы «ок» из обычного
 *     диалога не подтвердил визит на завтра),
 *   • только статус pending (confirmed уже подтверждён, cancelled
 *     не воскрешаем).
 */
const CONFIRM_WORDS = /^\s*[+✓✅]?\s*(да|yes|ok|okay|ок|оке|конечно|буду|приду|подтверждаю|confirmed?)\s*[!.]?\s*$/i

async function tryAutoConfirmAppointment(
  phone: string,
  text: string,
  clinicId: string,
): Promise<string | null> {
  if (text.length > 20) return null
  if (!CONFIRM_WORDS.test(text) && text.trim() !== '+') return null

  const db = admin()
  const tail = phone.slice(-10)
  const variants = Array.from(new Set([phone, `+${phone}`, tail, `+${tail}`]))
  const orExpr = variants.map((v) => `phones.cs.{${v}}`).join(',')
  const { data: pats } = await db
    .from('patients')
    .select('id')
    .eq('clinic_id', clinicId)
    .or(orExpr)
    .limit(5)
  if (!pats || pats.length === 0) return null

  const now = new Date()
  const in48h = new Date(now.getTime() + 48 * 3600_000)
  const todayIso = now.toISOString().slice(0, 10)
  const tomorrowIso = in48h.toISOString().slice(0, 10)

  const { data: appts } = await db
    .from('appointments')
    .select('id, date, time_start, status')
    .in('patient_id', pats.map((p: { id: string }) => p.id))
    .eq('status', 'pending')
    .gte('date', todayIso)
    .lte('date', tomorrowIso)
    .order('date', { ascending: true })
    .order('time_start', { ascending: true })
    .limit(1)
  if (!appts || appts.length === 0) return null

  const a = appts[0]
  const at = new Date(`${a.date}T${a.time_start}`)
  if (at < now || at > in48h) return null

  const { error } = await db
    .from('appointments')
    .update({ status: 'confirmed' })
    .eq('id', a.id)
    .eq('status', 'pending')
  if (error) {
    console.warn('[greenapi] auto-confirm update failed:', error.message)
    return null
  }
  console.log('[greenapi] auto-confirmed appointment', a.id, 'via reply from', phone)
  return a.id
}

/**
 * Скачать медиа-файл по downloadUrl из Green-API и переложить в наш Storage,
 * чтобы плеер в чате не зависел от CDN Green-API (там короткий TTL, бывает 403).
 * Возвращает { url, mime, size, name } или null если облом.
 */
async function ingestIncomingFile(
  clinicId: string,
  dealId: string,
  downloadUrl: string,
  mime: string | undefined,
  suggestedName: string | undefined,
): Promise<{ url: string; mime: string; size: number; name: string } | null> {
  try {
    const r = await fetch(downloadUrl)
    if (!r.ok) {
      console.warn('[greenapi] file fetch failed', r.status, downloadUrl)
      return null
    }
    const buf = Buffer.from(await r.arrayBuffer())
    const ct = mime || r.headers.get('content-type') || 'application/octet-stream'
    const ext = ct.includes('ogg')   ? 'ogg'
              : ct.includes('webm')  ? 'ogg'
              : ct.includes('mp4')   ? 'm4a'
              : ct.includes('mpeg')  ? 'mp3'
              : ct.includes('jpeg')  ? 'jpg'
              : ct.includes('png')   ? 'png'
              : ct.includes('pdf')   ? 'pdf'
              : 'bin'
    const fname = suggestedName || `in-${Date.now()}.${ext}`
    const path = `deals/${clinicId}/${dealId}/in-${Date.now()}.${ext}`
    const db = admin()
    const { error } = await db.storage.from('crm-attachments').upload(path, buf, {
      contentType: ct,
      upsert: false,
    })
    if (error) {
      console.warn('[greenapi] storage upload failed:', error.message)
      return null
    }
    const { data: pub } = db.storage.from('crm-attachments').getPublicUrl(path)
    return { url: pub.publicUrl, mime: ct, size: buf.length, name: fname }
  } catch (e) {
    console.warn('[greenapi] ingestIncomingFile error:', e)
    return null
  }
}

async function handleIncomingMessage(wh: IncomingMessageWebhook) {
  const db = admin()
  const phone = chatIdToPhone(wh.senderData.chatId)
  const text = extractIncomingText(wh)
  const waName = extractSenderName(wh.senderData)
  console.log(
    '[greenapi] incoming from', phone,
    waName ? `(${waName})` : '(no name)',
    '— text:', text?.slice(0, 80)
  )
  if (!text) return

  let deal = await findDealByPhone(phone)
  if (!deal) {
    console.log('[greenapi] no matching deal, creating inbound lead')
    deal = await createInboundDeal(phone, waName)
    if (!deal) {
      console.error('[greenapi] createInboundDeal returned null — no pipeline_stages?')
      return
    }
    console.log('[greenapi] created deal', deal.id, 'clinic', deal.clinic_id, 'name', deal.name)
  } else {
    console.log('[greenapi] matched existing deal', deal.id, 'name', deal.name)
    // Если раньше имени не было (была автогенерация), а сейчас пришло — обновим.
    await maybeBackfillDealName(deal.id, deal.name, phone, waName)
  }

  // Если это медиа (аудио/картинка/видео/документ) — скачиваем и сохраняем
  // в Storage, чтобы плеер/превью работали в чате CRM.
  type Attachment = { kind: 'voice' | 'image' | 'video' | 'file'; url: string; mime: string; size: number; name: string }
  const md = wh.messageData
  const fmd = md.fileMessageData
  let attachment: Attachment | null = null
  if (fmd?.downloadUrl) {
    const kind: Attachment['kind'] =
      md.typeMessage === 'audioMessage'    ? 'voice' :
      md.typeMessage === 'imageMessage'    ? 'image' :
      md.typeMessage === 'videoMessage'    ? 'video' :
                                              'file'
    const ingested = await ingestIncomingFile(
      deal.clinic_id, deal.id, fmd.downloadUrl, fmd.mimeType, fmd.fileName,
    )
    if (ingested) {
      attachment = { kind, ...ingested }
    }
  }

  // Пробуем полную вставку со статусом, если колонки ещё нет (миграция 040 не
  // применена) — откатываемся на минимальный набор полей.
  const basePayload = {
    deal_id: deal.id,
    clinic_id: deal.clinic_id,
    direction: 'in' as const,
    channel: 'whatsapp' as const,
    body: text,
    external_id: wh.idMessage,
    external_sender: waName ?? phone,
    created_at: new Date(wh.timestamp * 1000).toISOString(),
    ...(attachment ? { attachments: [attachment] } : {}),
  }

  let { error } = await db.from('deal_messages').insert({ ...basePayload, status: 'delivered' })
  if (error && /status|column/.test(error.message)) {
    console.warn('[greenapi] status column missing, retrying without it:', error.message)
    ;({ error } = await db.from('deal_messages').insert(basePayload))
  }
  if (error) {
    if (/duplicate/.test(error.message)) {
      console.log('[greenapi] duplicate message ignored:', wh.idMessage)
    } else {
      console.error('[greenapi] insert deal_messages failed:', error.message)
      throw new Error(error.message)
    }
  } else {
    console.log('[greenapi] message saved, deal', deal.id)
  }

  // Авто-подтверждение: если это короткий положительный ответ на напоминание,
  // находим ближайший pending-приём пациента и переводим в confirmed. Ошибки
  // глотаем — это побочный эффект, пусть не валит обработку сообщения.
  try {
    const confirmedId = await tryAutoConfirmAppointment(phone, text, deal.clinic_id)
    if (confirmedId) {
      // Лог в interactions, чтобы менеджер видел в истории сделки,
      // что подтверждение пришло автоматом.
      await db.from('crm_interactions').insert({
        clinic_id: deal.clinic_id,
        deal_id: deal.id,
        type: 'whatsapp',
        direction: 'inbound',
        summary: `Авто-подтверждение приёма по ответу "${text.slice(0, 40)}"`,
      })
    }
  } catch (e) {
    console.warn('[greenapi] auto-confirm flow failed (non-fatal):', e)
  }
}

async function handleOutgoingStatus(wh: OutgoingStatusWebhook) {
  const db = admin()
  const mapped =
    wh.status === 'sent'      ? 'sent' :
    wh.status === 'delivered' ? 'delivered' :
    wh.status === 'read'      ? 'read' :
    wh.status === 'failed' || wh.status === 'noAccount' || wh.status === 'notInGroup'
                              ? 'failed'
                              : null
  if (!mapped) return

  await db
    .from('deal_messages')
    .update({
      status: mapped,
      error_text: mapped === 'failed' ? `GreenAPI: ${wh.status}` : null,
    })
    .eq('external_id', wh.idMessage)
}

export async function POST(req: NextRequest) {
  // 1. Проверяем secret
  const secret = process.env.GREENAPI_WEBHOOK_TOKEN
  const token = req.nextUrl.searchParams.get('t') ?? req.headers.get('x-green-api-token')
  if (secret && token !== secret) {
    return NextResponse.json({ error: 'forbidden' }, { status: 403 })
  }

  // 2. Парсим
  let wh: GreenApiWebhook
  try {
    wh = await req.json()
  } catch {
    return NextResponse.json({ error: 'bad json' }, { status: 400 })
  }

  try {
    if (wh.typeWebhook === 'incomingMessageReceived') {
      await handleIncomingMessage(wh as IncomingMessageWebhook)
    } else if (wh.typeWebhook === 'outgoingMessageStatus') {
      await handleOutgoingStatus(wh as OutgoingStatusWebhook)
    } else if (wh.typeWebhook === 'stateInstanceChanged') {
      console.log('[greenapi] state:', (wh as { stateInstance?: string }).stateInstance)
    }
    return NextResponse.json({ ok: true })
  } catch (err) {
    console.error('[greenapi webhook] error:', err)
    // Возвращаем 200 чтобы GreenAPI не ретраил штормом, но событие
    // НЕ должно потеряться: пишем в webhook_errors (мигр. 082),
    // админ увидит непрочитанные в /settings/audit или прямым SELECT.
    try {
      const sb = admin()
      const errMsg = err instanceof Error ? err.message : String(err)
      const errCode = (err as { code?: string })?.code ?? null
      const externalId =
        (wh as { idMessage?: string })?.idMessage ??
        (wh as { senderData?: { idMessage?: string } })?.senderData?.idMessage ??
        null
      await sb.from('webhook_errors').insert({
        source: 'greenapi',
        event_type: wh.typeWebhook ?? null,
        external_id: externalId,
        error_message: errMsg,
        error_code: errCode,
        payload: wh as object,
        context: null,
      })
    } catch (logErr) {
      // Если даже лог-инсёрт упал — последняя надежда console.error,
      // оттуда Vercel logs. Большего сделать в этой точке нельзя.
      console.error('[greenapi webhook] failed to log error:', logErr)
    }
    return NextResponse.json({ ok: false, error: String(err) })
  }
}

// GreenAPI иногда делает GET /healthcheck — отвечаем 200
export async function GET() {
  return NextResponse.json({ ok: true, service: 'greenapi-webhook' })
}
